name: Build and tests with Node.js

on:
    push:
        branches: [main, renovate/**]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: 'npm'

            - run: npm i
            - run: npm run build
            - run: npm run test
